language: elixir
elixir:
  - 1.4.1
otp_release:
  - 19.0
deploy:
  provider: heroku
  api_key:
    secure: "b5kL6Cea1wpf4kabu2EhojUhJP9j0GqHH7sdH8NqmVlAxncD+JNfNa4Bpzi3Vy2Q9Bmy8ZjMaYKfo1V4nrykfk23mn4Ou1E+xoDCjH1Gp4cbGDGA0mJLMirTNDxx9Yjl8gq3LI/j/+cYvaaVb13YrxeHA/BHK28vtgWd6/60SgA3SEWxsJXMN+9gJL/dqEaH0AGNFDica1yzKpImxHVPsW3Cd23NlGEDRDgOr36i+6ezWt2I8mkbRjeoT2CUQR+tTCr4x4WOzur29OfVhkvk6BI0KV8FLWVXWnrk7W+5J/LILo0cyxUJ0C3/0pkCRpP+JplQ6pYYFI5bcSl+CMxSI0jGfEbFftaoB5j8E2CI/P8OnRKgLV2cJCd6uH+gK+nx09Y7HY5zX56gQAr9aznKCnDTduIRryvsMNBhEAOBbkqsuVDFcSfLDCkL1rtxoUvMEIu76/JTcjlNPwvHmOYXMlOGo+hywkD+V1cM8i9EHHTkpLFVzEG4o3AklbAAG7H2DrlwiTNT9K7gsgGkRa4T40TTZA5XVwtCcTqOd04c1Etb5zHztlGlzyb4e5I7DNddcHvaKf5cMg8dxEqA34FXiIqH1fpHMaLXYsSC26yvV0niCBn3d/NBcxdxfhZh9wtky8F33uvou1GD82tk/5IWkNZXB47WUgDwCD1oIZZLlJE="
